export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_CHAT = 'ADD_CHAT';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const ADD_MESSAGE_TO_LIB = 'ADD_MESSAGE_TO_LIB';
export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_IN_LIB = 'DELETE_MESSAGE_IN_LIB';